module.exports = {
  title: "Dust",
  description: "Hello :) test",
  author: "Birdust",
  siteUrl: "https://birdust.github.io",
  links: {
    github: "https://github.com/Birdust",
    linkedIn: "https://linkedin.com",
    facebook: "https://www.facebook.com",
    twitter: "https://twitter.com",
    x: "https://x.com",
    instagram: "https://www.instagram.com",
    medium: "https://medium.com",
    blogger: "https://blogger.com",
    email: "djswl0922@gmail.com",
    resume: "https://birdust.github.io/resume/",
    link: "https://github.com/Birdust",
  },
  useAbout: true,
  // See https://giscus.app/
  giscus: {
    repo: "Birdust/Birdust.github.io",
    repoId: "R_kgDOHZl3Kg=",
    category: "Comments",
    categoryId: "",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
